name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: install llvm (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y libc++-20-dev libc++abi-20-dev
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100

      - name: install llvm (macos)
        if: matrix.os == 'macos-latest'
        run: brew install llvm

      - uses: xmake-io/github-action-setup-xmake@v1

      - name: configure (windows)
        if: matrix.os == 'windows-latest'
        run: xmake config -m release --cc="C:/Program Files/LLVM/bin/clang++" --cxx="C:/Program Files/LLVM/bin/clang++"

      - name: configure (unix)
        if: matrix.os != 'windows-latest'
        run: xmake config -m release --cc=clang++ --cxx=clang++

      - name: build
        run: xmake

      - name: run
        run: xmake run
